### ISSUE TITLE
Todo for v3 Release

### ISSUE THREAD

**Issue by AdelKS** [AdelKS/ZeGrapher#1]
- [x] Add new math functions, from c++11 norm (erf, gamma... etc)
- [x] Save user preferences:
  - [x] Settings
  - [x] Functions' and sequences' colors
- [x] Implement new integrated error message system for functions and sequences.
- [x] Added "Default curve color" entry in settings window: the user can now choose the default color given to any new added mathematical object.
- [x] Pressing Enter after editing a cell in a data window will get the focus on the next lower cell.
- [x] In data tables: selecting cells with the mouse then hitting Delete or Backspace will empty them
- [x] Write help documents in English and French for the data windows (since there are a lot of hidden possibilites)
- [x] Remove data rows when emptied by keyboard deletion.
- [x] Bug tracking, testing
  - [x] Polynomial Fit move apart when the asked degree is too big: with the current way to calculate fits, the double data type is not precise enough for that: programmed a new way to calculate which is more precise, but still moves apart starting from the 20th degree.
  - [x] A lot of bugs fixed... (check the commits if interested)
  - [x] Fix scroll freeze issue
- [x] Export from values table
- [x] Update check module
- [x] Update the website with the new version's description
- [x] Compile for Windows, Linux and Mac
- [x] Release!

Released! :laughing:

**Comment by mickael-bosch** [comment]
Salut Adel,

Je pense toujours à ton logiciel mais comme je l'ai dit sur le forum, je 
n'ai pas beaucoup de temps en ce moment. Je fais des tours sur Qtfr pour 
faire des poses au milieu de mon !$#;:!!!^¨#~ de boulot. J'aime bien mon 
boulot mais en ce moment, je fais tout ce que n'aime pas en informatique.
Bref, je n'avance pas sur ZeGrapher pour l'instant mais je le garde bien 
en tête.

Je teste au passage le fait de répondre sur l'adresse renseignée par github,
Bonne soirée,
Mickael

On 02/08/2015 14:33, Adel Kara Slimane wrote:
>
>   * Ajouter les nouvelles fonctions mathématiques dans c++11 (erf et
>     compagnie)
>   * Enregistrer les préférences utilisateur avec QSettings
>   * Prendre en compte les widgets d'étalement manuel de l'affichage
>     des régressions
>   * Ajouter les fenêtres d'aide là où il ya les boutons d'aide: il
>     faudra aussi traduire et voir là où il y a un réel besoin d'aide
>     pour y mettre des boutons d'aide.
>
> Ce Todo n'est pas définitif et sera mis à jour au fur et à mesures que 
> des bugs seront à corriger, ou des corrections à ajouter
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AdelKS/ZeGrapher/issues/1>.
>

-- 
Logo HL2 group 	*Mickaël Bosch*
2 Avenue Galilée
86961, Chasseneuil Futuroscope, France, map
<https://www.google.com/maps/place/46.657505,0.365330> +33 6 33 60 83 24
mickael.bosch@hl2.com <mailto:veronique.enault@hl2.com>


This message and any attachment are confidential and may be privileged 
or otherwise protected from disclosure. If you are not the intended 
recipient, please telephone or email the sender and delete this message 
and any attachment from your system. If you are not the intended 
recipient you must not copy this message or attachment or disclose the 
contents to any other person. Any dissemination, duplication, 
publication to third parties or other use of the contents of this e-mail 
is forbidden. Although this information has been compiled with great 
care, HL2 group shall not accept any responsibility for any errors, 
omissions or other inaccuracies in this information or for the 
consequences thereof, nor shall it be bound in any way by the contents 
of this email.

**Comment by AdelKS** [comment]
Salut Mickael,

Haha je vois. Non non il n'y a pas à t'inquiéter sur ZeGrapher, quand tu as
le temps et la motivation de faire quelque chose, tu es le bienvenu! Sinon,
il n'y a pas de problème, j'avance à mon rythme et toi toi aussi. Et de
toute façon, pour l'instant, je n'ai pas encore fini cette version pour
qu'on se fixe des objectifs pour la prochaine version, pour lesquels
ensuite on travaillera, quand chacun le sentira. C'est là tout l'intérêt de
la chose, il faut voir ça comme un passe temps de retraité.

Sinon, bon courage avec ton boulot! Et je teste aussi le fait de pouvoir te
répondre avec ce que Github m'a envoyé comme destinataire de réponse. Mais
je le vois aussi sur le ticket "Todo for v3 release"
<https://github.com/AdelKS/ZeGrapher/issues/1#>, cela veut dire que votre
réponse (que je viens de lire) et celle-ci que vous êtes en train de lire
sont publiques.
Bonne soirée à vous aussi.
Adel.
